#!/usr/bin/env python

Import("env")
Import("env_modules")

env_libopenmpt = env_modules.Clone()


thirdparty_dir = "#thirdparty/libopenmpt/"

# Treat libopenmpt headers as system headers to avoid raising warnings. Not supported on MSVC.
if not env.msvc:
    env_libopenmpt.Append(CPPFLAGS=["-isystem", Dir(thirdparty_dir).path])
else:
    env_libopenmpt.Prepend(CPPPATH=[thirdparty_dir])

# Godot source files
env_libopenmpt.add_source_files(env.modules_sources, "*.cpp")