#!/usr/bin/env python

Import("env")
Import("env_modules")

env_goostmidi = env_modules.Clone()

# Godot source files
env_goostmidi.add_source_files(env.modules_sources, "*.cpp")
env_goostmidi.add_source_files(env.modules_sources, "docs/*.cpp")
if env.editor_build:
    env_goostmidi.add_source_files(env.modules_sources, "icons/*.cpp")
